### ISSUE TITLE
Incorrect Madau reddening formulation

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/DESC_BPZ#1]
@adam-broussard identified a problem with the `etau_madau` function in bpz-1.99.3, and I've confirmed that the same implementation bug persisted to the python3 version of BPZ, and thus DESC_BPZ.  We need to replace the `desc_bpz/bpz_tools_py3.py` function `etau_madau` with updated code that properly returns the footnote 3 formulation of intergalactic extinction from Madau (1995).

Thankfully, some quick googling reveals that Dan Coe (one of the developers of BPZ) wrote out an improved version of etau_madau for STScI Synphot package:
https://github.com/spacetelescope/synphot_refactor/issues/77

So, we just need to replace the old etau_madau with this proper code, which I tested, and does produce a proper reddening curve.

**Comment by sschmidt23** [comment]
I am noticing that at wavelengths shorter than the Lyman Limit exp(-tau) looks to go positive, which doesn't seem correct.  Actually, the entire uptick in exp(-tau) as it approaches the Lyman Limit seems wrong to me. I highly doubt that we'll ever have wavelength measurements in the Far UV like this, but it is a little worrisome. I'll put a note in the code about it.

**Comment by sschmidt23** [comment]
closed by #2

**Comment by adam-broussard** [comment]
I know that this is closed, but I found that adding `tau[lam_obs < lam_obs[argmax(tau)]] = max(tau)` at the end of the `etau_madau()` function prevents the upturn at low wavelengths

**Comment by sschmidt23** [comment]
I almost implemented a simplified version of this, but hesitated because then it is different from the form in Madau 1995.  But, it really is unphysical, particularly since it jumps up to values >1 for Tau, so it would actually add flux to the template.  So, yeah, after thinking about it overnight I'll reopen and add this line to the code, along with a note in the doc string.

**Comment by sschmidt23** [comment]
Implemented the hack and tested, closed by #3
